version: "3"

tasks:
    clear-prod:
        dir: $HOME/.krolus
        cmds:
            - cmd: rm -f ./*
              silent: true
    clear-dev:
        dir: ./db
        cmds:
            - cmd: rm -f ./*
              silent: true
    migrate:
        dir: ./migrations
        cmds:
            - cmd: go build -o migrate
              silent: true
    export-prod:
        deps: [migrate, clear-prod]
        dir: ./migrations
        cmds:
            - ./migrate -export=true -production=true -file=mine.xml
    export-dev:
        deps: [migrate, clear-dev]
        dir: ./migrations
        cmds:
            - ./migrate -export=true -production=false -file=test.xml
    import-prod:
        deps: [migrate, clear-prod]
        dir: ./migrations
        cmds:
            - ./migrate -export=false -production=true -file=mine.xml
    import-dev:
        deps: [migrate, clear-dev]
        dir: ./migrations
        cmds:
            - ./migrate -export=false -production=false -file=test.xml
    web:
        dir: ./front/frontend
        cmds:
            - npx ng serve
    browser:
        dir: ./front
        cmds:
            - go build -o wview
            - ./wview
    serve:
        cmds:
            - wails serve
    build:
        cmds:
            - wails build
    deploy:
        # deps: [build]
        dir: ./build
        cmds:
            - cp krolus $HOME/Apps
