version: "3"

tasks:
    migrate:
        cmds:
            - rm ./db/*
            - cd ./migrations; go build -o migrate
            - ./migrations/migrate
    web:
        cmds:
            - cd ./front/frontend;  npx ng serve
    front:
        cmds:
            - cd ./front; go build -o wview
            - ./front/wview
    serve:
        cmds:
            - wails serve
    build:
        cmds:
            - wails build
